# Generated by Django 5.0.6 on 2025-09-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
