# Generated by Django 5.0.6 on 2025-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
